### ISSUE TITLE
Authentication 기능 분리

### ISSUE THREAD

**Issue by middlefitting** [middlefitting/TheForum-ApiGateway#1]
# [FEAT] Authentication

## 제안 사항
현재 Authentication 기능을 MainService에서도 수행하고 있는 상황입니다.
해당 기능은 apigateway에서 일괄적으로 수행하도록 기능을 추가합니다.

##Todo
- [ ] 토큰 발급 기능 추가
- [ ] 토큰 인증 기능 유지보수
- [ ] 테스트 코드 작성
